apiVersion: apps/v1

kind: Deployment

metadata:
  name: backend-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend

          image: 103021623558.dkr.ecr.ap-south-1.amazonaws.com/mern-ecommerce-backend:v1

          ports:
            - containerPort: 5000